<?php $wallet = Mage::helper('latipay')->getWalletData(); ?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="latipay-payment">
        <span class="latipay-payment__info"><?php echo $this->__('You will be redirected to Latipay after order confirmation.'); ?></span>
        <br/>
        <span class="latipay-payment__info"><?php echo $this->__('Latipay offers the above options to make a secure payment.'); ?></span>
        <ul class="latipay-options">
            <?php foreach ($wallet as $wkey => $wvalue) : ?>
                <?php $paymentName = strtolower($wvalue); ?>
                <li class="latipay-options-item">
                    <input name="payment[latipay_method]" id="latipay-method-<?php echo $paymentName; ?>" type="radio" value="<?php echo $paymentName; ?>">
                    <label for="latipay-method-<?php echo $paymentName; ?>"><?php echo 'Pay by ' . $wvalue; ?></label>
                    <div id="<?php echo $paymentName ?>-section" style="display: none;">
                        <img style="max-width: 200px;  vertical-align: middle; margin-bottom: 10px;" src="<?php echo Mage::helper('latipay')->getLogoByPaymentName($paymentName) ?>" />
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>

<script type="text/javascript">
    (function($, window, document) {
        var paymentRadioName = 'input[name="payment[latipay_method]"]',
            prevBlockId = '#' + $(paymentRadioName).first().val() + '-section';
        // initialize the condition
        // First option will be checked and the logo area is visiable
        $(paymentRadioName).first().attr('checked', 'checked');
        $(prevBlockId).show();

        $(paymentRadioName).on('change', function () {
            var paymentName     = $(this).val(),
                paymentInfoId   = '#' + paymentName + '-section';
                // hide prev block
                if (prevBlockId != paymentInfoId) {
                    $(prevBlockId).hide();
                }
                // show current
                $(paymentInfoId).show();
                prevBlockId = paymentInfoId;
        });
    })(jQuery, window, document);
</script>